/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import scene.Scene;
import javax.swing.JButton;
import main.EngineGame;
import scene.SceneTable;
import java.util.ArrayList;

/**
 * SceneFrame extends the class JFrame and adds on extra features needed for
 * Dungeon Escape.
 * @author sra0004
 */
public class SceneFrame extends javax.swing.JFrame {  
    
    private ArrayList<Scene> sceneList;
    private int[] buttonVis;
    int currentIdx;
    int nextIdx;
    private SceneTable scenetable;
    Scene currentScene;
    
    /**
     * Creates new form SceneFrame
     */
    public SceneFrame() {  
        sceneList = new ArrayList<Scene>();
        buttonVis = null;
        initComponents(); 
        nextIdx= -1;
        scenetable = new SceneTable();
        scenetable.initTable();
        currentIdx = 0;
    }   
    /**
     * addScene adds an instance of Scene to SceneManager
     * @param aScene
     * @param idx 
     */
    public void addScene(Scene aScene, int idx){
        
        sceneList.add(idx, aScene);
        
        if(idx == 0)
        {
            SceneManager.add(aScene, idx); 
        }
    }
    
    
    /**
     * displayScene adds the current scene to be displayed to an ArrayList of
     * scenes used to organize them.
     * @param idx 
     */
    public void displayScene(int idx){
        
        if (idx != -1)
        {
            currentScene = sceneList.get(idx);
            currentScene.displayEvents();
            SceneManager.getComponent(0).setVisible(false);
            SceneManager.remove(0);
            //currentScene = (Scene)SceneManager.getComponent(idx);            
            
            SceneManager.add(currentScene);
            SceneManager.getComponent(0).setVisible(true);
            
            //SceneManager.getComponent(currentIdx).setVisible(false);
            
            currentScene.displayEvents();
      
            currentIdx = idx;
        }
    }
    //public void displayScene(Scene)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SceneManager1 = new scene.ScenePanel();
        SceneManager = new scene.ScenePanel();
        frameTorchButton = new javax.swing.JButton();
        frameKeyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ForwardButton = new javax.swing.JButton();
        LeftButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        frameSwordButton = new javax.swing.JButton();

        javax.swing.GroupLayout SceneManager1Layout = new javax.swing.GroupLayout(SceneManager1);
        SceneManager1.setLayout(SceneManager1Layout);
        SceneManager1Layout.setHorizontalGroup(
            SceneManager1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SceneManager1Layout.setVerticalGroup(
            SceneManager1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adventure Game");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 0, 255));
        setForeground(new java.awt.Color(255, 51, 51));

        SceneManager.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout SceneManagerLayout = new javax.swing.GroupLayout(SceneManager);
        SceneManager.setLayout(SceneManagerLayout);
        SceneManagerLayout.setHorizontalGroup(
            SceneManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        SceneManagerLayout.setVerticalGroup(
            SceneManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        frameTorchButton.setBackground(new java.awt.Color(51, 51, 51));
        frameTorchButton.setForeground(new java.awt.Color(102, 102, 102));
        frameTorchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/torch2.png"))); // NOI18N
        frameTorchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameTorchButton.setEnabled(false);
        frameTorchButton.setFocusable(false);
        frameTorchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameTorchButtonActionPerformed(evt);
            }
        });

        frameKeyButton.setBackground(new java.awt.Color(51, 51, 51));
        frameKeyButton.setForeground(new java.awt.Color(102, 102, 102));
        frameKeyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/key.png"))); // NOI18N
        frameKeyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameKeyButton.setEnabled(false);
        frameKeyButton.setFocusable(false);
        frameKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameKeyButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        ForwardButton.setText("Forward");
        ForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardButtonActionPerformed(evt);
            }
        });

        LeftButton.setText("Left");
        LeftButton.setPreferredSize(new java.awt.Dimension(73, 23));
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        RightButton.setText("Right");
        RightButton.setMaximumSize(new java.awt.Dimension(73, 23));
        RightButton.setPreferredSize(new java.awt.Dimension(73, 23));
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.setPreferredSize(new java.awt.Dimension(73, 23));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        frameSwordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Steel_sword_icon.png"))); // NOI18N
        frameSwordButton.setEnabled(false);
        frameSwordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameSwordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SceneManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frameTorchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frameKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(frameSwordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ForwardButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SceneManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(frameTorchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frameKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(frameSwordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ForwardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frameTorchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameTorchButtonActionPerformed
   currentScene=sceneList.get(currentIdx);
   currentScene.isDark=false;
   currentScene.updateButtons();
   this.displayScene(currentIdx);
   currentScene.updateDirectionButtons();
   currentScene.updateSceneText();
   
    }//GEN-LAST:event_frameTorchButtonActionPerformed
    /**
     * frameKeybutton calls the functions needed to use the key to unlock doors. 
     * @param evt 
     */
    private void frameKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameKeyButtonActionPerformed
   currentScene=sceneList.get(currentIdx);
   currentScene.isClosed=false;
   this.displayScene(currentIdx);
   currentScene.updateDirectionButtons();
   currentScene.updateSceneText();
    }//GEN-LAST:event_frameKeyButtonActionPerformed
    /**
     * ForwardButton calls all of the necessary functions to travel forward
     * within the dungeon.
     * @param evt 
     */
    private void ForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardButtonActionPerformed
        nextIdx = scenetable.changeScene(currentIdx, 0);
        this.displayScene(nextIdx);
        currentScene.updateDirectionButtons();
        currentScene.updateSceneText();
    }//GEN-LAST:event_ForwardButtonActionPerformed
    /**
     * LeftButton calls all of the necessary functions to travel to the right
     * within the dungeon.
     * @param evt 
     */
    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        nextIdx = scenetable.changeScene(currentIdx, 3);
        this.displayScene(nextIdx);
        currentScene.updateDirectionButtons();
        currentScene.updateSceneText();
        
    }//GEN-LAST:event_LeftButtonActionPerformed
    /**
     * RightButton calls all of the necessary functions to travel to the right
     * within the dungeon.
     * @param evt 
     */
    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        nextIdx = scenetable.changeScene(currentIdx, 2);
        this.displayScene(nextIdx);
        currentScene.updateDirectionButtons();
        currentScene.updateSceneText();
    }//GEN-LAST:event_RightButtonActionPerformed
    /**
     * BackButton calls all the necessary functions to travel backwards within
     * the dungeon.
     * @param evt 
     */
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        nextIdx = scenetable.changeScene(currentIdx, 1);
        this.displayScene(nextIdx);
        currentScene.updateDirectionButtons();
        currentScene.updateSceneText();
    }//GEN-LAST:event_BackButtonActionPerformed
    /**
     * frameSwordButton is the button denoted by a sword icon on main jFrame.
     * @param evt 
     */
    private void frameSwordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameSwordButtonActionPerformed
   currentScene=sceneList.get(currentIdx);
   currentScene.isAlive=false;
   this.displayScene(currentIdx);
   currentScene.updateDirectionButtons();
   currentScene.updateSceneText();
    }//GEN-LAST:event_frameSwordButtonActionPerformed
    /**
     * setTextArea is called in the constructor of each scene to set the textbox
     * for each scene.
     * @param TA 
     */
    public void setTextArea(String TA){
        jTextArea1.setText(TA);
    }
    /**
     * repaintScene() is called to repaint a scene after a choice that alters a
     * scene is made.
     */
    public void repaintScene(){
        this.displayScene(currentIdx);
    }

    /**
     * updateDirections enables and disables buttons based on the directions you
     * can travel in each scene.
     * @param forward
     * @param back
     * @param left
     * @param right 
     */
    public void updateDirections(boolean forward, boolean back, boolean left, boolean right){
        ForwardButton.setEnabled(forward);
        BackButton.setEnabled(back);
        LeftButton.setEnabled(left);
        RightButton.setEnabled(right);
        
    }
    
    
    /**
     * updateSceneText will get the text to be displayed in each scene
     * describing what is happening and pointing out any important features.
     * @param text 
     */
    public void updateSceneText(String text){
        jTextArea1.setText(text);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ForwardButton;
    private javax.swing.JButton LeftButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JPanel SceneManager;
    private javax.swing.JPanel SceneManager1;
    public javax.swing.JButton frameKeyButton;
    public javax.swing.JButton frameSwordButton;
    public javax.swing.JButton frameTorchButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
